apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: template
spec:
  params:
    - name: repository
      description: The git repo
    - name: branch
      description: the branch for the git repo
    - name: apikey
      description: the ibmcloud api key
    - name: zosSshKey
      description: The z/OS SSH private key
    - name: appName
      description: The application name
      default: CICS-GENAPP-TEKTON
    - name: pipeline-debug
      default: "0"
    - name: registryNamespace
      description: the ibmcloud registry namespace
    - name: registryRegion
      description: the ibmcloud registry region
      default: us-south
    - name: cluster
      description: The IBM Cloud Kubernetes cluster name
    - name: clusterRegion
      description: The IBM Cloud Kubernetes cluster region
      default: us-south
    - name: clusterNamespace
      description: The Kubernetes cluster namespace
      default: prod
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage:  5Gi
        volumeMode: Filesystem
        storageClassName: tekton-local-storage
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
            name: pipeline
        workspaces:
          - name: pipeline-ws
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc
        podTemplate:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
        params:
        - name: repository
          value: $(params.repository)
        - name: branch
          value: $(params.branch)
        - name: apikey
          value: $(params.apikey)
        - name: zosSshKey
          value: $(params.zosSshKey)
        - name: appName
          value: $(params.appName)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: registryNamespace
          value: $(params.registryNamespace)
        - name: registryRegion
          value: $(params.registryRegion)
        - name: cluster
          value: $(params.cluster)
        - name: clusterRegion
          value: $(params.clusterRegion)
        - name: clusterNamespace
          value: $(params.clusterNamespace)
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: binding
spec:
  params:
    - name: repository
      value: "https://github.com/jbyibm/dbb-pipeline"
    - name: branch
      value: "ibmcloud-tekton"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: listener
spec:
  triggers:
    - binding:
        name: binding
      template:
        name: template
