apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline
spec:
  params:
    - name: repository
      description: the git repo
    - name: revision
      description: the branch for the git repo
    - name: apikey
      description: the ibmcloud api key
    - name: zosSshKey
      description: The z/OS SSH private key
    - name: appName
      description: The application name
      default: CICS-GENAPP-TEKTON
    - name: registryRegion
      description: the ibmcloud registry region
      default: us-south
    - name: clusterRegion
      description: The IBM Cloud Kubernetes cluster region
      default: us-south
    - name: clusterNamespace
      description: The Kubernetes cluster namespace
      default: prod
  workspaces:
  - name: pipeline-pvc
  tasks:
    - name: clone-task
      taskRef:
        name: git-clone-repo
      params:
        - name: continuous-delivery-context-secret
          value: "secure-properties"
        - name: ibmcloud-apikey-secret-key
          value: "toolchain-apikey"
        - name: repository
          value: $(params.repository)
        - name: branch
          value: $(params.branch)
        - name: pipeline-debug
          value: $(params.pipeline-debug)
        - name: properties-file
          value: ""
      workspaces:
        - name: output
          workspace: pipeline-ws
    - name: pipeline-dbb-build-task
      runAfter: [clone-task]
      taskRef:
        name: dbb-build-task
      params:
        - name: repository
          value: $(params.repository)
        - name: revision
          value: $(params.revision)
        - name: apikey
          value: $(params.apikey)
        - name: zosSshKey
          value: $(params.zosSshKey)
        - name: appName
          value: $(params.appName)
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc