apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: dbb-build-task
spec:
  params:
    - name: repository
      description: the git repo
    - name: revision
      description: the revision
      default: master
    - name: apikey
      description: the ibmcloud api key
    - name: zosSshKey
      description: The z/OS SSH private key
    - name: appName
      description: The application name
  workspaces:
  - name: task-pvc
    mountPath: /artifacts
  steps:
    - name: dbb-build
      image: ibmcom/pipeline-base-image
      env:
        - name: REPOSITORY
          value: $(params.repository)
        - name: REVISION
          value: $(params.revision)
        - name: IBMCLOUD_API_KEY
          value: $(params.apikey)
        - name: ZOS_SSH_KEY
          value: $(params.zosSshKey)
        - name: MY_APP_NAME
          value: $(params.appName)
      script: |
        #!/bin/bash
        env
        echo $ZOS_SSH_KEY | base64 -w 0 --decode > id_rsa
        chmod 700 id_rsa
        ssh -i id_rsa -o "StrictHostKeyChecking=no" jenkins@zdevops-demo1.fyre.ibm.com\
           -p 222 "/u/jenkins/ibmcloud/build.sh $BUILD_NUMBER"
        rc=$?
        
        mkdir zoslog
        cd zoslog
        sftp -o "StrictHostKeyChecking=no"  -i ../id_rsa  -P 222 jenkins@zdevops-demo1.fyre.ibm.com<<EOF
        mget /u/jenkins/ibmcloud/dbb-pipeline/BUILD-$BUILD_NUMBER/*/*
        EOF
        cd ..
        
        ibmcloud plugin install -f doi
        echo $IBMCLOUD_API_KEY
        ibmcloud login --apikey $IBMCLOUD_API_KEY --no-region
        ibmcloud doi publishbuildrecord --logicalappname="$MY_APP_NAME" --buildnumber="$MY_BUILD_NUMBER" --branch="$GIT_BRANCH" --repositoryurl="$GIT_URL" --commitid="$GIT_COMMIT" --status=pass
        
        
        for file in $(find  zoslog -name "*.xml")
        do
          ibmcloud doi publishtestrecord --logicalappname="$MY_APP_NAME" --buildnumber="$MY_BUILD_NUMBER" --filelocation=$file --type=unittest
        done
        
        rm -f id_rsa